# Generated by Django 3.1.7 on 2021-02-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=256)),
                ('phone', models.PositiveBigIntegerField()),
                ('address', models.CharField(max_length=512)),
                ('city', models.CharField(choices=[('Bangalore', 'Bangalore')], default='Bangalore', max_length=256)),
                ('pincode', models.PositiveBigIntegerField()),
            ],
        ),
    ]
